name: Three Jobs Example

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Building Application"

  test:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Running Tests"

  deploy:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Deploying Application"
